In [1]:
import pandas as pd
import janitor
import os

In [2]:
os.listdir("../data/fpl_data")

['fpl_2020_21.csv',
 'fpl_2020_21.xlsx',
 'fpl_2021_22.csv',
 'fpl_2021_22.xlsx',
 'fpl_2022_23.csv',
 'fpl_2022_23.xlsx',
 'fpl_2023_24.csv',
 'fpl_2023_24.xlsx',
 'full_df.csv',
 'full_df.xlsx']

In [3]:
df = pd.DataFrame()

In [4]:
df

Empty DataFrame
Columns: []
Index: []

In [5]:
for data in os.listdir("../data/fpl_data"):
    if ".csv" in data and "fpl" in data:
        new_df = pd.read_csv("../data/fpl_data/" + data, encoding="utf8")
        new_df["season"] = str(data).split(".")[0][-7:]
        df = pd.concat([df, new_df], axis = 0)
df = df.reset_index(drop=True)

In [6]:
df

,name,position,team,xP,assists,bonus,bps,clean_sheets,creativity,element,...,value,was_home,yellow_cards,GW,season,expected_assists,expected_goal_involvements,expected_goals,expected_goals_conceded,starts
0,Aaron Connolly,FWD,Brighton,0.5,0,0,-3,0,0.3,78,...,55,True,0,1,2020_21,NaN,NaN,NaN,NaN,NaN
1,Aaron Cresswell,DEF,West Ham,2.1,0,0,11,0,11.2,435,...,50,True,0,1,2020_21,NaN,NaN,NaN,NaN,NaN
2,Aaron Mooy,MID,Brighton,0.0,0,0,0,0,0.0,60,...,50,True,0,1,2020_21,NaN,NaN,NaN,NaN,NaN
3,Aaron Ramsdale,GK,Sheffield Utd,2.5,0,0,12,0,0.0,483,...,50,True,0,1,2020_21,NaN,NaN,NaN,NaN,NaN
4,Abdoulaye Doucour√©,MID,Everton,1.3,0,0,20,1,44.6,512,...,55,False,0,1,2020_21,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
93194,Kyle Walker,DEF,Man City,3.7,0,0,16,0,36.5,369,...,55,False,0,23,2023_24,0.12,0.14,0.02,1.02,1.0
93195,Jacob Brown,FWD,Luton,-0.7,0,0,1,0,0.5,631,...,49,False,0,23,2023_24,0.00,0.05,0.05,0.19,0.0
93196,Vicente Guaita,GK,Crystal Palace,0.0,0,0,0,0,0.0,227,...,44,False,0,23,2023_24,0.00,0.00,0.00,0.00,0.0
93197,Braian Ojeda Rodr√≠guez,MID,Nott'm Forest,0.0,0,0,0,0,0.0,459,...,45,False,0,23,2023_24,0.00,0.00,0.00,0.00,0.0
93198,Mads Bech S√∏rensen,DEF,Brentford,0.0,0,0,0,0,0.0,93,...,40,True,0,23,2023_24,0.00,0.00,0.00,0.00,0.0

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 93199 entries, 0 to 93198
Data columns (total 42 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   name                        93199 non-null  object
 1   position                    93199 non-null  object
 2   team                        93199 non-null  object
 3   xP                          93199 non-null  float64
 4   assists                     93199 non-null  int64
 5   bonus                       93199 non-null  int64
 6   bps                         93199 non-null  int64
 7   clean_sheets                93199 non-null  int64
 8   creativity                  93199 non-null  float64
 9   element                     93199 non-null  int64
 10  fixture                     93199 non-null  int64
 11  goals_conceded              93199 non-null  int64
 12  goals_scored                93199 non-null  int64
 13  ict_index                   93199 non-null  float64
 14  influence                   93199 non-null  float64
 15  kickoff_time                93199 non-null  object
 16  minutes                     93199 non-null  int64
 17  opponent_team               93199 non-null  int64
 18  own_goals                   93199 non-null  int64
 19  penalties_missed            93199 non-null  int64
 20  penalties_saved             93199 non-null  int64
 21  red_cards                   93199 non-null  int64
 22  round                       93199 non-null  int64
 23  saves                       93199 non-null  int64
 24  selected                    93199 non-null  int64
 25  team_a_score                93199 non-null  int64
 26  team_h_score                93199 non-null  int64
 27  threat                      93199 non-null  float64
 28  total_points                93199 non-null  int64
 29  transfers_balance           93199 non-null  int64
 30  transfers_in                93199 non-null  int64
 31  transfers_out               93199 non-null  int64
 32  value                       93199 non-null  int64
 33  was_home                    93199 non-null  bool
 34  yellow_cards                93199 non-null  int64
 35  GW                          93199 non-null  int64
 36  season                      93199 non-null  object
 37  expected_assists            43387 non-null  float64
 38  expected_goal_involvements  43387 non-null  float64
 39  expected_goals              43387 non-null  float64
 40  expected_goals_conceded     43387 non-null  float64
 41  starts                      43387 non-null  float64
dtypes: bool(1), float64(10), int64(26), object(5)
memory usage: 29.2+ MB

In [8]:
df.to_csv("../data/fpl_data/full_df.csv", index=False, encoding="utf8")

In [9]:
df["team"].unique()

array(['Brighton', 'West Ham', 'Sheffield Utd', 'Everton', 'Fulham',
       'Wolves', 'Leeds', 'Leicester', 'Liverpool', 'West Brom',
       'Arsenal', 'Southampton', 'Newcastle', 'Chelsea', 'Crystal Palace',
       'Spurs', 'Man Utd', 'Man City', 'Aston Villa', 'Burnley',
       'Watford', 'Norwich', 'Brentford', 'Bournemouth', "Nott'm Forest",
       'Luton'], dtype=object)

In [10]:
len(df["team"].unique())

26

In [11]:
df[[df["season"] == "2023_24"] and df["position"]=="FWD"].tail(20)

,name,position,team,xP,assists,bonus,bps,clean_sheets,creativity,element,...,value,was_home,yellow_cards,GW,season,expected_assists,expected_goal_involvements,expected_goals,expected_goals_conceded,starts
93038,Cameron Archer,FWD,Sheffield Utd,0.5,0,0,5,0,1.7,33,...,43,True,0,23,2023_24,0.03,0.15,0.12,0.37,0.0
93061,Carlton Morris,FWD,Luton,6.7,1,2,45,0,21.4,326,...,50,False,0,23,2023_24,0.14,0.96,0.82,2.09,1.0
93068,Cauley Woodrow,FWD,Luton,-0.3,0,0,1,0,0.3,340,...,43,False,0,23,2023_24,0.00,0.00,0.00,0.03,0.0
93070,Harry Kane,FWD,Spurs,0.0,0,0,0,0,0.0,500,...,125,False,0,23,2023_24,0.00,0.00,0.00,0.00,0.0
93072,Antoine Semenyo,FWD,Bournemouth,1.0,0,0,1,0,10.8,82,...,45,True,0,23,2023_24,0.01,0.02,0.01,0.50,1.0
93077,Darwin N√∫√±ez Ribeiro,FWD,Liverpool,3.2,0,0,0,0,0.1,293,...,75,False,1,23,2023_24,0.00,0.02,0.02,1.42,0.0
93080,Folarin Balogun,FWD,Arsenal,0.0,0,0,0,0,0.0,1,...,44,True,0,23,2023_24,0.00,0.00,0.00,0.00,0.0
93105,Nathan Fraser,FWD,Wolves,0.3,0,0,0,0,0.0,704,...,45,False,0,23,2023_24,0.00,0.00,0.00,0.00,0.0
93119,Romelu Lukaku Bolingoli,FWD,Chelsea,0.0,0,0,0,0,0.0,207,...,68,True,0,23,2023_24,0.00,0.00,0.00,0.00,0.0
93124,Deniz Undav,FWD,Brighton,0.0,0,0,0,0,0.0,149,...,55,True,0,23,2023_24,0.00,0.00,0.00,0.00,0.0
93128,Christopher Nkunku,FWD,Chelsea,2.3,0,0,3,0,15.6,212,...,74,True,0,23,2023_24,0.01,0.63,0.62,0.93,1.0
93136,B√©nie Traor√©,FWD,Sheffield Utd,0.0,0,0,0,0,0.0,593,...,51,True,0,23,2023_24,0.00,0.00,0.00,0.00,0.0
93142,Odsonne Edouard,FWD,Crystal Palace,0.7,0,0,3,0,10.1,225,...,54,False,0,23,2023_24,0.00,0.00,0.00,0.60,0.0
93146,Lyle Foster,FWD,Burnley,1.7,0,0,11,0,1.8,168,...,47,True,0,23,2023_24,0.02,0.03,0.01,1.28,1.0
93156,Sasa Kalajdzic,FWD,Wolves,0.0,0,0,0,0,0.0,562,...,49,False,0,23,2023_24,0.00,0.00,0.00,0.00,0.0
93167,Armando Broja,FWD,Fulham,1.0,0,0,2,0,0.5,193,...,49,False,0,23,2023_24,0.00,0.00,0.00,0.16,0.0
93168,Dominic Solanke,FWD,Bournemouth,4.0,0,0,5,0,13.3,85,...,71,True,0,23,2023_24,0.02,0.02,0.00,0.56,1.0
93169,Chris Wood,FWD,Nott'm Forest,2.2,0,0,0,0,0.0,468,...,50,False,0,23,2023_24,0.00,0.00,0.00,0.00,0.0
93184,Ronnie Stutter,FWD,Chelsea,0.0,0,0,0,0,0.0,717,...,45,True,0,23,2023_24,0.00,0.00,0.00,0.00,0.0
93195,Jacob Brown,FWD,Luton,-0.7,0,0,1,0,0.5,631,...,49,False,0,23,2023_24,0.00,0.05,0.05,0.19,0.0